Repository team-joytas/wooco-be, pull requests merged in 2024-12, with the labels that each got.

#4 feat: 레이어 컨벤션 설정 및 공용 로직 추가
  build.gradle.kts
  gradle.properties
  settings.gradle.kts
  src/main/kotlin/kr/wooco/woocobe/common/config/IdGeneratorConfig.kt
  src/main/kotlin/kr/wooco/woocobe/common/domain/IdGenerator.kt
  src/main/kotlin/kr/wooco/woocobe/common/domain/UseCase.kt
  src/main/kotlin/kr/wooco/woocobe/common/storage/BaseTimeEntity.kt
  src/main/resources/application-local.yml
Labels: feature

#7 feat: PR 템플릿 및 개발 컨벤션 설정과 스크립트 추가
  .editorconfig
  .github/CODEOWNERS
  .github/pull_request_template.md
  Makefile
  build.gradle.kts
  gradle.properties
  script/pre-commit.sh
  settings.gradle.kts
  src/main/kotlin/kr/wooco/woocobe/common/config/IdGeneratorConfig.kt
  src/main/kotlin/kr/wooco/woocobe/common/domain/IdGenerator.kt
  src/main/kotlin/kr/wooco/woocobe/common/domain/UseCase.kt
  src/main/kotlin/kr/wooco/woocobe/common/storage/BaseTimeEntity.kt
  src/test/kotlin/kr/wooco/woocobe/WoocoBeApplicationTests.kt
Labels: feature

#8 feat: 사용자 생성 기능 추가
  src/main/kotlin/kr/wooco/woocobe/user/domain/gateway/UserStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/user/domain/model/User.kt
  src/main/kotlin/kr/wooco/woocobe/user/infrastructure/gateway/JpaUserStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/user/infrastructure/storage/UserEntity.kt
  src/main/kotlin/kr/wooco/woocobe/user/infrastructure/storage/UserJpaRepository.kt
Labels: feature

#10 test: 테스트 코드 초기 구성 추가
  docker/docker-compose.yml
  docker/init.sql
  src/test/kotlin/kr/wooco/woocobe/support/KotestConfig.kt
  src/test/kotlin/kr/wooco/woocobe/support/MysqlCleaner.kt
  src/test/kotlin/kr/wooco/woocobe/support/RedisCleaner.kt
  src/test/kotlin/kr/wooco/woocobe/support/TestAnnotation.kt
  src/test/resources/application-test.yml
  src/test/resources/kotest.properties
Labels: test

#12 feat: 인증 도메인 로직 및 구현체 추가
  build.gradle.kts
  gradle.properties
  src/main/kotlin/kr/wooco/woocobe/auth/domain/gateway/AuthTokenStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/gateway/AuthUserStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/gateway/SocialAuthClientGateway.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/gateway/TokenProviderGateway.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/model/AuthToken.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/model/AuthUser.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/model/SocialAuthInfo.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/model/SocialAuthType.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/usecase/LogoutUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/usecase/ReissueTokenUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/usecase/SocialLoginUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/client/KakaoOAuthRestClient.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/client/dto/KakaoOAuthInfoResponse.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/gateway/JpaAuthUserStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/gateway/JwtTokenProviderGateway.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/gateway/RedisAuthTokenStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/gateway/RestSocialAuthClientGateway.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/storage/AuthUserEntity.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/storage/AuthUserJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/token/JWTProvider.kt
  src/main/kotlin/kr/wooco/woocobe/auth/ui/web/AuthController.kt
  src/main/kotlin/kr/wooco/woocobe/common/config/RestClientConfig.kt
  src/main/kotlin/kr/wooco/woocobe/common/utils/RedisOperatorExtensions.kt
  src/main/resources/application-local.yml
  src/test/kotlin/kr/wooco/woocobe/auth/domain/usecase/LogoutUseCaseTest.kt
  src/test/kotlin/kr/wooco/woocobe/auth/domain/usecase/ReissueTokenUseCaseTest.kt
  src/test/kotlin/kr/wooco/woocobe/auth/domain/usecase/SocialLoginUseCaseTest.kt
Labels: feature

#17 feat: 로깅 필터 및 예외 클래스 추가
  src/main/kotlin/kr/wooco/woocobe/common/config/LoggingConfig.kt
  src/main/kotlin/kr/wooco/woocobe/common/exception/BaseErrorCode.kt
  src/main/kotlin/kr/wooco/woocobe/common/exception/CustomException.kt
  src/main/kotlin/kr/wooco/woocobe/common/exception/GlobalExceptionHandler.kt
  src/main/kotlin/kr/wooco/woocobe/common/logging/MdcLoggingFilter.kt
  src/main/kotlin/kr/wooco/woocobe/common/logging/ReqResLoggingFilter.kt
Labels: feature

#19 feat: 스프링 시큐리티 추가 및 인증 API 추가
  build.gradle.kts
  src/main/kotlin/kr/wooco/woocobe/auth/ui/web/AuthController.kt
  src/main/kotlin/kr/wooco/woocobe/auth/ui/web/dto/request/LoginRequest.kt
  src/main/kotlin/kr/wooco/woocobe/auth/ui/web/dto/response/ReissueTokenResponse.kt
  src/main/kotlin/kr/wooco/woocobe/auth/ui/web/dto/response/SocialLoginResponse.kt
  src/main/kotlin/kr/wooco/woocobe/common/config/SecurityConfig.kt
  src/main/kotlin/kr/wooco/woocobe/common/exception/GlobalExceptionHandler.kt
  src/main/kotlin/kr/wooco/woocobe/common/security/AuthIgnorePaths.kt
  src/main/kotlin/kr/wooco/woocobe/common/security/JwtAuthenticationFilter.kt
  src/main/resources/application-local.yml
Labels: feature

#18 feat: 플랜 생성 기능 추가
  src/main/kotlin/kr/wooco/woocobe/plan/domain/gateway/PlanStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/model/Plan.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/model/PlanRegionInfo.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/gateway/JpaPlanStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/PlanEntity.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/PlanJpaRepository.kt
Labels: feature

#21 feat: 쿠키 핸들링 확장 함수 추가 및 적용
  src/main/kotlin/kr/wooco/woocobe/WoocoBeApplication.kt
  src/main/kotlin/kr/wooco/woocobe/auth/ui/web/AuthController.kt
  src/main/kotlin/kr/wooco/woocobe/common/utils/CookieExtensions.kt
  src/main/kotlin/kr/wooco/woocobe/common/utils/SpringContextLoader.kt
  src/main/resources/application-local.yml
Labels: feature

#26 feat: QueryDSL 설정 추가 및 TSID 라이브러리 변경
  build.gradle.kts
  gradle.properties
  settings.gradle.kts
  src/main/kotlin/kr/wooco/woocobe/common/config/QueryDslConfig.kt
Labels: feature

#27 feat: 코스 도메인 기능 추가
  src/main/kotlin/kr/wooco/woocobe/course/domain/gateway/CourseStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/model/Course.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/model/CourseCategory.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/model/CourseRegion.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/model/CourseSortCondition.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/AddCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/DeleteCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetAllCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetUserAllCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/UpdateCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/gateway/JpaCourseStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseCategoryEntity.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseCategoryJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseCustomRepository.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseCustomRepositoryImpl.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseEntity.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseJpaRepository.kt
Labels: feature

#24 feat: 플랜 도메인 기본 CRUD 기능 추가
  src/main/kotlin/kr/wooco/woocobe/plan/domain/gateway/PlanStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/model/Plan.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/model/PlanDate.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/model/PlanRegion.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/model/PlanRegionInfo.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/usecase/AddPlanUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/usecase/DeletePlanUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/usecase/GetAllPlanUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/usecase/GetPlanUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/usecase/UpdatePlanUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/gateway/JpaPlanStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/PlanEntity.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/PlanJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/plan/ui/web/PlanController.kt
  src/main/kotlin/kr/wooco/woocobe/plan/ui/web/dto/request/AddPlanRequest.kt
  src/main/kotlin/kr/wooco/woocobe/plan/ui/web/dto/request/UpdatePlanRequest.kt
  src/main/kotlin/kr/wooco/woocobe/plan/ui/web/dto/response/GetAllPlanResponse.kt
  src/main/kotlin/kr/wooco/woocobe/plan/ui/web/dto/response/GetPlanResponse.kt
Labels: feature

#29 feat: 관심 코스 및 코스 댓글 도메인 기능 추가
  src/main/kotlin/kr/wooco/woocobe/course/domain/gateway/CourseCommentStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/gateway/InterestCourseStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/model/CourseComment.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/model/InterestCourse.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/AddCourseCommentUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/AddInterestCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/DeleteCourseCommentUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/DeleteInterestCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetAllCourseCommentUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetAllMyInterestCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/UpdateCourseCommentUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/gateway/JpaCourseCommentStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/gateway/JpaInterestCourseStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseCommentEntity.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseCommentJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/InterestCourseEntity.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/InterestCourseJpaRepository.kt
Labels: feature

#32 refactor: 플랜 도메인에서 유저 연관 관계 및 의존성 리팩토링
  src/main/kotlin/kr/wooco/woocobe/plan/domain/model/Plan.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/model/PlanDate.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/usecase/AddPlanUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/usecase/GetAllPlanUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/usecase/GetPlanUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/usecase/UpdatePlanUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/gateway/JpaPlanStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/PlanEntity.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/PlanJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/plan/ui/web/PlanController.kt
  src/main/kotlin/kr/wooco/woocobe/plan/ui/web/dto/response/GetAllPlanResponse.kt
  src/main/kotlin/kr/wooco/woocobe/plan/ui/web/dto/response/GetPlanResponse.kt
Labels: refactor

#33 feat: 회원 기능 추가
  src/main/kotlin/kr/wooco/woocobe/user/domain/gateway/UserStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/user/domain/model/User.kt
  src/main/kotlin/kr/wooco/woocobe/user/domain/usecase/GetUserUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/user/domain/usecase/UpdateUserUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/user/infrastructure/gateway/JpaUserStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/user/infrastructure/storage/UserEntity.kt
  src/main/kotlin/kr/wooco/woocobe/user/ui/web/UserController.kt
  src/main/kotlin/kr/wooco/woocobe/user/ui/web/dto/request/UpdateUserProfileRequest.kt
  src/main/kotlin/kr/wooco/woocobe/user/ui/web/dto/response/GetCurrentUserResponse.kt
  src/test/kotlin/kr/wooco/woocobe/user/domain/usecase/GetUserUseCaseTest.kt
  src/test/kotlin/kr/wooco/woocobe/user/domain/usecase/UpdateUserUseCaseTest.kt
Labels: feature

#40 feat: CI 테스트 환경 구성 추가
  .github/workflows/pull-request-ci.yml
  src/test/kotlin/kr/wooco/woocobe/support/MysqlCleaner.kt
  src/test/resources/application-test.yml
Labels: feature

#36 feat: 장소 및 장소 리뷰 관련 기능 추가
  src/main/kotlin/kr/wooco/woocobe/place/domain/gateway/PlaceReviewStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/gateway/PlaceStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/model/Place.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/model/PlaceOneLineReview.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/model/PlaceReview.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/AddPlaceReviewUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/AddPlaceUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/DeletePlaceReviewUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/GetAllPlaceReviewUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/GetPlaceReviewUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/GetPlaceUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/GetUserAllPlaceReviewUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/UpdatePlaceReviewUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/ValidateReviewWriterUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/gateway/JpaPlaceReviewStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/gateway/JpaPlaceStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceEntity.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceOneLineReviewEntity.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceOneLineReviewJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceReviewEntity.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceReviewImageEntity.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceReviewJpaRepository.kt
Labels: feature

#42 chore: pre-commit 설정 로직 변경
  Makefile
  build.gradle.kts
  scripts/commit-msg
Labels: chore

#44 fix: 플레이스 컴파일 오류 해결
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/gateway/JpaPlaceReviewStorageGateway.kt
Labels: fix

#46 refactor: 공용 패키지 구성 변경
  src/main/kotlin/kr/wooco/woocobe/auth/domain/usecase/LogoutUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/usecase/ReissueTokenUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/usecase/SocialLoginUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/usecase/WithdrawUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/storage/AuthTokenEntity.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/storage/AuthUserEntity.kt
  src/main/kotlin/kr/wooco/woocobe/common/domain/exception/BaseErrorCode.kt
  src/main/kotlin/kr/wooco/woocobe/common/domain/exception/CustomException.kt
  src/main/kotlin/kr/wooco/woocobe/common/domain/usecase/UseCase.kt
  src/main/kotlin/kr/wooco/woocobe/common/infrastructure/client/RestClientConfig.kt
  src/main/kotlin/kr/wooco/woocobe/common/infrastructure/storage/BaseTimeEntity.kt
  src/main/kotlin/kr/wooco/woocobe/common/infrastructure/storage/IdGenerator.kt
  src/main/kotlin/kr/wooco/woocobe/common/infrastructure/storage/IdGeneratorConfig.kt
  src/main/kotlin/kr/wooco/woocobe/common/infrastructure/storage/QueryDslConfig.kt
  src/main/kotlin/kr/wooco/woocobe/common/ui/logging/LoggingConfig.kt
  src/main/kotlin/kr/wooco/woocobe/common/ui/logging/MdcLoggingFilter.kt
  src/main/kotlin/kr/wooco/woocobe/common/ui/logging/ReqResLoggingFilter.kt
  src/main/kotlin/kr/wooco/woocobe/common/ui/security/AuthIgnorePaths.kt
  src/main/kotlin/kr/wooco/woocobe/common/ui/security/JwtAuthenticationFilter.kt
  src/main/kotlin/kr/wooco/woocobe/common/ui/security/SecurityConfig.kt
  src/main/kotlin/kr/wooco/woocobe/common/ui/web/GlobalExceptionAdvice.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/AddCourseCommentUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/AddCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/AddInterestCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/DeleteCourseCommentUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/DeleteCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/DeleteInterestCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetAllCourseCommentUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetAllCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetAllMyInterestCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetUserAllCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/UpdateCourseCommentUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/UpdateCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseCategoryEntity.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseCommentEntity.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseEntity.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/InterestCourseEntity.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/AddPlaceReviewUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/AddPlaceUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/DeletePlaceReviewUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/GetAllPlaceReviewUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/GetPlaceReviewUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/GetPlaceUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/GetUserAllPlaceReviewUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/UpdatePlaceReviewUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/ValidateReviewWriterUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceEntity.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceOneLineReviewEntity.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceReviewEntity.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/usecase/AddPlanUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/usecase/DeletePlanUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/usecase/GetAllPlanUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/usecase/GetPlanUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/usecase/UpdatePlanUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/PlanEntity.kt
  src/main/kotlin/kr/wooco/woocobe/user/domain/usecase/GetUserUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/user/domain/usecase/UpdateUserUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/user/infrastructure/storage/UserEntity.kt
Labels: refactor, style

#48 feat: 카카오맵 장소 ID로 장소 조회 기능 추가
  src/main/kotlin/kr/wooco/woocobe/place/domain/gateway/PlaceStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/gateway/JpaPlaceStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceJpaRepository.kt
Labels: feature

#50 refactor: QueryDSL에서 JDSL으로 마이그레이션
  build.gradle.kts
  gradle.properties
  settings.gradle.kts
  src/main/kotlin/kr/wooco/woocobe/common/infrastructure/storage/JdslConfig.kt
  src/main/kotlin/kr/wooco/woocobe/common/infrastructure/storage/QueryDslConfig.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseCustomRepositoryImpl.kt
Labels: refactor, feature

#57 fix: Github Actions CI 스크립트 캐싱 오류 수정
  .github/workflows/pull-request-ci.yml
Labels: fix

#54 feat: 장소 리뷰 도메인 평점 계산 및 한줄평 통계 조회 기능 추가
  src/main/kotlin/kr/wooco/woocobe/place/domain/gateway/PlaceOneLineReviewStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/model/Place.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/model/PlaceOneLineReviewStat.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/AddPlaceReviewUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/DeletePlaceReviewUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/GetOneLineReviewStatsUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/UpdatePlaceReviewUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/gateway/JpaPlaceOneLineReviewStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/gateway/JpaPlaceReviewStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceOneLineReviewEntity.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceOneLineReviewJpaRepository.kt
Labels: fix, refactor, feature

#55 feat: 전역 API 응답 설정 및 스웨거 추가
  build.gradle.kts
  gradle.properties
  src/main/kotlin/kr/wooco/woocobe/auth/ui/config/AuthIgnorePaths.kt
  src/main/kotlin/kr/wooco/woocobe/common/domain/exception/BaseErrorCode.kt
  src/main/kotlin/kr/wooco/woocobe/common/ui/config/JacksonConfig.kt
  src/main/kotlin/kr/wooco/woocobe/common/ui/config/SwaggerConfig.kt
  src/main/kotlin/kr/wooco/woocobe/common/ui/web/GlobalApiResponseAdvice.kt
  src/main/kotlin/kr/wooco/woocobe/common/ui/web/GlobalExceptionAdvice.kt
  src/main/resources/application-local.yml
Labels: feature
