Repository team-joytas/wooco-be, pull requests merged in 2025-06, with the labels that each got.

#229 build: 스프링 보안 업데이트 적용 및 MySQL 벌크 설정 추가
  gradle.properties
  infrastructure/mysql/src/main/resources/application-mysql.yml
Labels: build

#231 refactor: 알림 기능 애그리거트 리팩토링
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/application/port/in/results/NotificationResult.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/application/service/NotificationCommandService.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/domain/entity/DeviceToken.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/domain/entity/Notification.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/domain/vo/Target.kt
  infrastructure/fcm/src/main/kotlin/kr/wooco/woocobe/fcm/notification/FcmNotificationSenderAdapter.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/notification/NotificationPersistenceMapper.kt
Labels: refactor

#232 hotfix: 좋아요 수 카운트 쿼리 및 배포 스크립트 수정
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/course/repository/CourseLikeJpaRepository.kt
Labels: hotfix, patch

#235 release: v1.0.2 릴리즈
  .github/release-drafter.config.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release-label-checker.yml
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/application/port/in/results/NotificationResult.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/application/service/NotificationCommandService.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/domain/entity/DeviceToken.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/domain/entity/Notification.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/domain/vo/Target.kt
  infrastructure/fcm/src/main/kotlin/kr/wooco/woocobe/fcm/notification/FcmNotificationSenderAdapter.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/notification/NotificationPersistenceMapper.kt
Labels: chore, release, patch
