Repository team-joytas/wooco-be, pull requests merged in 2025-02, with the labels that each got.

#134 refactor: 회원 기능 패키지 구조 수정
  src/main/kotlin/kr/wooco/woocobe/auth/domain/usecase/SocialLoginUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/usecase/WithdrawUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/response/CourseCommentDetailResponse.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/response/CourseDetailResponse.kt
  src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/response/PlaceReviewDetailsResponse.kt
  src/main/kotlin/kr/wooco/woocobe/user/adapter/in/web/UserApi.kt
  src/main/kotlin/kr/wooco/woocobe/user/adapter/in/web/UserController.kt
  src/main/kotlin/kr/wooco/woocobe/user/adapter/in/web/request/UpdateUserRequest.kt
  src/main/kotlin/kr/wooco/woocobe/user/adapter/in/web/response/UserDetailResponse.kt
  src/main/kotlin/kr/wooco/woocobe/user/adapter/out/persistence/UserPersistenceAdapter.kt
  src/main/kotlin/kr/wooco/woocobe/user/adapter/out/persistence/UserPersistenceMapper.kt
  src/main/kotlin/kr/wooco/woocobe/user/adapter/out/persistence/entity/UserJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/user/adapter/out/persistence/repository/UserJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/user/application/port/in/ReadUserUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/user/application/port/in/UpdateUserProfileUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/user/application/port/in/WithdrawUserUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/user/application/port/in/results/UserResult.kt
  src/main/kotlin/kr/wooco/woocobe/user/application/port/out/DeleteUserPersistencePort.kt
  src/main/kotlin/kr/wooco/woocobe/user/application/port/out/LoadUserPersistencePort.kt
  src/main/kotlin/kr/wooco/woocobe/user/application/port/out/SaveUserPersistencePort.kt
  src/main/kotlin/kr/wooco/woocobe/user/application/service/UserCommandService.kt
  src/main/kotlin/kr/wooco/woocobe/user/application/service/UserQueryService.kt
  src/main/kotlin/kr/wooco/woocobe/user/domain/entity/User.kt
  src/main/kotlin/kr/wooco/woocobe/user/domain/gateway/UserStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/user/domain/model/User.kt
  src/main/kotlin/kr/wooco/woocobe/user/domain/usecase/GetAllUserUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/user/domain/usecase/GetUserUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/user/domain/usecase/UpdateUserUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/user/infrastructure/gateway/UserStorageGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/user/infrastructure/storage/UserStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/user/infrastructure/storage/repository/UserJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/user/ui/web/controller/response/UserDetailResponse.kt
  src/main/kotlin/kr/wooco/woocobe/user/ui/web/facade/UserFacadeService.kt
  src/test/kotlin/kr/wooco/woocobe/auth/domain/usecase/SocialLoginUseCaseTest.kt
  src/test/kotlin/kr/wooco/woocobe/auth/domain/usecase/WithdrawUseCaseTest.kt
  src/test/kotlin/kr/wooco/woocobe/user/domain/usecase/GetUserUseCaseTest.kt
  src/test/kotlin/kr/wooco/woocobe/user/domain/usecase/UpdateUserUseCaseTest.kt
Labels: refactor

#138 refactor: 코스 댓글 분리 및 패키지 구조 수정
  src/main/kotlin/kr/wooco/woocobe/course/domain/gateway/CourseCommentStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/model/CourseComment.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/AddCourseCommentUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/DeleteCourseCommentUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetAllCourseCommentUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/UpdateCourseCommentUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/gateway/CourseCommentStorageGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/CourseCommentController.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/request/UpdateCourseCommentRequest.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/response/CreateCourseCommentResponse.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/facade/CourseCommentCommandFacade.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/facade/CourseCommentQueryFacade.kt
  src/main/kotlin/kr/wooco/woocobe/coursecomment/adapter/in/web/CourseCommentApi.kt
  src/main/kotlin/kr/wooco/woocobe/coursecomment/adapter/in/web/CourseCommentController.kt
  src/main/kotlin/kr/wooco/woocobe/coursecomment/adapter/in/web/request/CreateCourseCommentRequest.kt
  src/main/kotlin/kr/wooco/woocobe/coursecomment/adapter/in/web/request/UpdateCourseCommentRequest.kt
  src/main/kotlin/kr/wooco/woocobe/coursecomment/adapter/in/web/response/CourseCommentDetailResponse.kt
  src/main/kotlin/kr/wooco/woocobe/coursecomment/adapter/in/web/response/CreateCourseCommentResponse.kt
  src/main/kotlin/kr/wooco/woocobe/coursecomment/adapter/out/persistence/CourseCommentPersistenceAdapter.kt
  src/main/kotlin/kr/wooco/woocobe/coursecomment/adapter/out/persistence/CourseCommentPersistenceMapper.kt
  src/main/kotlin/kr/wooco/woocobe/coursecomment/adapter/out/persistence/entity/CourseCommentJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/coursecomment/adapter/out/persistence/repository/CourseCommentJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/coursecomment/application/port/in/CreateCourseCommentUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/coursecomment/application/port/in/DeleteCourseCommentUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/coursecomment/application/port/in/ReadAllCourseCommentUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/coursecomment/application/port/in/UpdateCourseCommentUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/coursecomment/application/port/in/results/CourseCommentResult.kt
  src/main/kotlin/kr/wooco/woocobe/coursecomment/application/port/out/DeleteCourseCommentPersistencePort.kt
  src/main/kotlin/kr/wooco/woocobe/coursecomment/application/port/out/LoadCourseCommentPersistencePort.kt
  src/main/kotlin/kr/wooco/woocobe/coursecomment/application/port/out/SaveCourseCommentPersistencePort.kt
  src/main/kotlin/kr/wooco/woocobe/coursecomment/application/service/CourseCommentCommandService.kt
  src/main/kotlin/kr/wooco/woocobe/coursecomment/application/service/CourseCommentQueryService.kt
  src/main/kotlin/kr/wooco/woocobe/coursecomment/domain/entity/CourseComment.kt
  src/main/kotlin/kr/wooco/woocobe/coursecomment/domain/exception/CourseCommentExceptions.kt
Labels: refactor

#139 refactor: 회원 프로필 검증 로직 수정 및 상태 추가
  src/main/kotlin/kr/wooco/woocobe/user/adapter/in/web/response/UserDetailResponse.kt
  src/main/kotlin/kr/wooco/woocobe/user/adapter/out/persistence/UserPersistenceMapper.kt
  src/main/kotlin/kr/wooco/woocobe/user/adapter/out/persistence/entity/UserJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/user/application/port/in/results/UserResult.kt
  src/main/kotlin/kr/wooco/woocobe/user/application/service/UserCommandService.kt
  src/main/kotlin/kr/wooco/woocobe/user/domain/entity/User.kt
  src/main/kotlin/kr/wooco/woocobe/user/domain/vo/UserProfile.kt
  src/main/kotlin/kr/wooco/woocobe/user/domain/vo/UserStatus.kt
Labels: fix, refactor

#150 fix: PlaceResult contents 매핑 오류 수정
  src/main/kotlin/kr/wooco/woocobe/place/application/port/in/result/PlaceResult.kt
Labels: fix

#151 refactor: 플랜 패키지 구조 수정
  src/main/kotlin/kr/wooco/woocobe/plan/adapter/in/web/request/CreatePlanRequest.kt
  src/main/kotlin/kr/wooco/woocobe/plan/adapter/in/web/request/UpdatePlanRequest.kt
  src/main/kotlin/kr/wooco/woocobe/plan/adapter/in/web/response/PlanDetailResponse.kt
  src/main/kotlin/kr/wooco/woocobe/plan/adapter/out/persistence/PlanCategoryPersistenceMapper.kt
  src/main/kotlin/kr/wooco/woocobe/plan/adapter/out/persistence/PlanPersistenceAdapter.kt
  src/main/kotlin/kr/wooco/woocobe/plan/adapter/out/persistence/PlanPersistenceMapper.kt
  src/main/kotlin/kr/wooco/woocobe/plan/adapter/out/persistence/PlanPlacePersistenceMapper.kt
  src/main/kotlin/kr/wooco/woocobe/plan/adapter/out/persistence/entity/PlanCategoryJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/plan/adapter/out/persistence/repository/PlanCategoryJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/plan/application/port/in/CreatePlanUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/plan/application/port/in/UpdatePlanUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/plan/application/port/in/results/PlanResult.kt
  src/main/kotlin/kr/wooco/woocobe/plan/application/service/PlanCommandService.kt
  src/main/kotlin/kr/wooco/woocobe/plan/application/service/PlanQueryService.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/entity/Plan.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/entity/PlanCategory.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/entity/PlanRegion.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/exception/PlanExceptions.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/vo/PlanPlace.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/vo/PlanRegion.kt
Labels: refactor

#157 chore: firebase 환경 세팅 추가
  .gitignore
  bootstrap/api/build.gradle.kts
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/WoocoBeApplication.kt
  bootstrap/api/src/main/resources/application.yml
  gradle.properties
  infrastructure/fcm/build.gradle.kts
  infrastructure/fcm/src/main/kotlin/kr/wooco/woocobe/fcm/common/config/FcmConfig.kt
  infrastructure/fcm/src/main/resources/application-fcm.yml
  settings.gradle.kts
Labels: chore, build

#161 refactor: 장소 리뷰 이벤트 핸들링 및 한줄평 데이터 관리 구조 개선
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/placereview/response/PlaceReviewDetailsResponse.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/place/application/handler/PlaceEventHandler.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/place/application/port/in/result/PlaceResult.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/place/application/service/PlaceQueryService.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/place/domain/entity/Place.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/port/in/result/PlaceReviewResult.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/port/out/DeleteAllPlaceOneLineReviewPersistencePort.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/port/out/LoadPlaceOneLineReviewPersistencePort.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/port/out/LoadPlaceOneLineReviewStatPersistencePort.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/port/out/SaveAllPlaceOneLineReviewPersistencePort.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/service/PlaceReviewCommandService.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/service/PlaceReviewQueryService.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/service/dto/PlaceOneLineReviewStat.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/domain/entity/PlaceOneLineReview.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/domain/entity/PlaceReview.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/domain/event/PlaceReviewCreateEvent.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/domain/event/PlaceReviewDeleteEvent.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/domain/event/PlaceReviewUpdateEvent.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/placereview/PlaceOneLineReviewPersistenceAdapter.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/placereview/PlaceOneLineReviewPersistenceMapper.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/placereview/PlaceOneLineReviewStatPersistenceAdapter.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/placereview/PlaceOneLineReviewStatPersistenceMapper.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/placereview/PlaceReviewPersistenceAdapter.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/placereview/PlaceReviewPersistenceMapper.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/placereview/entity/PlaceOneLineReviewStatJpaEntity.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/placereview/repository/PlaceOneLineReviewJpaRepository.kt
Labels: refactor

#163 fix: 한줄평 통계 Repository 삭제
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/placereview/repository/PlaceOneLineReviewStatJpaRepository.kt
Labels: fix

#164 feat: 댓글 생성 이벤트 발행 로직 추가
  core/src/main/kotlin/kr/wooco/woocobe/core/coursecomment/application/service/CourseCommentCommandService.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/coursecomment/domain/event/CourseCommentCreateEvent.kt
Labels: feature

#167 feat: 스프링 비동기 쓰레드 설정 추가
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/common/config/AsyncConfig.kt
  bootstrap/api/src/main/resources/application.yml
Labels: feature

#168 refactor: 댓글 생성 이벤트 필드 수정
  core/src/main/kotlin/kr/wooco/woocobe/core/coursecomment/domain/event/CourseCommentCreateEvent.kt
Labels: refactor

#169 feat: 알림 도메인 기능 추가
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/WoocoBeApplication.kt
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/notification/NotificationApi.kt
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/notification/NotificationController.kt
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/notification/request/CreateDeviceTokenRequest.kt
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/notification/response/NotificationDetailResponse.kt
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/plan/PlanApi.kt
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/plan/PlanController.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/common/config/SchedulingConfig.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/application/handler/NotificationEventHandler.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/application/port/in/CreateDeviceTokenUseCase.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/application/port/in/CreateNotificationUseCase.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/application/port/in/DeleteDeviceTokenUseCase.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/application/port/in/ReadAllNotificationUseCase.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/application/port/in/ReadDeviceTokenUseCase.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/application/port/in/UpdateNotificationUseCase.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/application/port/in/results/DeviceTokenResult.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/application/port/in/results/NotificationResult.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/application/port/out/DeleteDeviceTokenPersistencePort.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/application/port/out/LoadDeviceTokenPersistencePort.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/application/port/out/LoadNotificationPersistencePort.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/application/port/out/SaveDeviceTokenPersistencePort.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/application/port/out/SaveNotificationPersistencePort.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/application/port/out/SendNotificationPort.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/application/service/NotificationCommandService.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/application/service/NotificationQueryService.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/domain/entity/DeviceToken.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/domain/entity/Notification.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/domain/exception/NotificationExceptions.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/domain/vo/NotificationType.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/plan/application/port/in/SharePlanUseCase.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/plan/application/port/out/LoadPlanPersistencePort.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/plan/application/scheduler/PlanScheduler.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/plan/application/service/PlanCommandService.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/plan/domain/entity/Plan.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/plan/domain/event/PlanShareRequestEvent.kt
  infrastructure/fcm/src/main/kotlin/kr/wooco/woocobe/fcm/notification/SendNotificationFcmAdapter.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/notification/DeviceTokenPersistenceAdapter.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/notification/DeviceTokenPersistenceMapper.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/notification/NotificationPersistenceAdapter.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/notification/NotificationPersistenceMapper.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/notification/entity/DeviceTokenJpaEntity.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/notification/entity/NotificationJpaEntity.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/notification/repository/DeviceTokenJpaRepository.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/notification/repository/NotificationJpaRepository.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/plan/PlanPersistenceAdapter.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/plan/PlanPersistenceMapper.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/plan/entity/PlanJpaEntity.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/plan/repository/PlanJpaRepository.kt
Labels: feature

#172 feat: 장소 썸네일 이미지 추출 로직 추가
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/place/PlaceController.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/place/application/handler/PlaceEventHandler.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/place/application/port/in/CreatePlaceIfNotExistsUseCase.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/place/application/port/in/UpdatePlaceImageUseCase.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/place/application/port/out/PlaceClientPort.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/place/application/service/PlaceCommandService.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/place/domain/entity/Place.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/place/domain/event/PlaceCreateEvent.kt
  infrastructure/rest/src/main/kotlin/kr/wooco/woocobe/rest/common/config/RestConfig.kt
  infrastructure/rest/src/main/kotlin/kr/wooco/woocobe/rest/place/GooglePlaceApiClient.kt
  infrastructure/rest/src/main/kotlin/kr/wooco/woocobe/rest/place/GooglePlaceProperties.kt
  infrastructure/rest/src/main/kotlin/kr/wooco/woocobe/rest/place/PlaceClientAdapter.kt
  infrastructure/rest/src/main/kotlin/kr/wooco/woocobe/rest/place/response/GooglePlaceDetailsResponse.kt
  infrastructure/rest/src/main/kotlin/kr/wooco/woocobe/rest/place/response/GooglePlaceIdResponse.kt
  infrastructure/rest/src/main/resources/application-rest.yml
Labels: feature

#178 build: 스크립트내 환경변수 관리 로직 수정 및 메트릭 모듈 추가
  .github/workflows/deploy-dev.yml
  .github/workflows/pr-ci-test.yml
  bootstrap/api/build.gradle.kts
Labels: chore, build

#182 fix: 과도한 플랜 공유 알림 생성으로 인한 스케줄링 주기 변경
  core/src/main/kotlin/kr/wooco/woocobe/core/plan/application/scheduler/PlanScheduler.kt
Labels: hotfix
