Repository team-joytas/wooco-be, pull requests merged in 2025-04, with the labels that each got.

#211 refactor: 알림, 플랜 도메인 soft delete 적용 및 네이밍 변경
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/application/port/out/DeviceTokenCommandPort.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/application/service/NotificationCommandService.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/domain/entity/DeviceToken.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/domain/entity/Notification.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/domain/vo/DeviceTokenStatus.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/domain/vo/NotificationStatus.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/plan/application/port/out/PlanCommandPort.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/plan/application/service/PlanCommandService.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/plan/domain/entity/Plan.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/plan/domain/vo/PlanStatus.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/notification/DeviceTokenJpaAdapter.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/notification/DeviceTokenJpaMapper.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/notification/NotificationJpaAdapter.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/notification/NotificationJpaMapper.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/notification/entity/DeviceTokenJpaEntity.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/notification/entity/NotificationJpaEntity.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/notification/repository/DeviceTokenJpaRepository.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/notification/repository/NotificationJpaRepository.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/plan/PlanJpaAdapter.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/plan/PlanJpaMapper.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/plan/PlanPlaceJpaMapper.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/plan/entity/PlanJpaEntity.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/plan/repository/PlanJpaRepository.kt
  infrastructure/mysql/src/main/resources/db/migration/V4__add_status_notifications_and_plans.sql
Labels: refactor

#214 refactor: 이벤트 발행 로직 개선
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/common/config/AsyncConfig.kt
  core/build.gradle.kts
  core/src/main/kotlin/kr/wooco/woocobe/core/common/aspect/EventPublisherAspect.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/common/domain/entity/AggregateRoot.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/common/domain/entity/DomainEntity.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/common/domain/event/DomainEvent.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/common/advice/CustomJpaRepositoryFactoryBean.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/common/advice/EventPublishingMethodInterceptor.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/common/config/MysqlConfig.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/common/entity/BaseEntity.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/common/utils/Tsid.kt
  support/common/src/main/kotlin/kr/wooco/woocobe/common/event/Event.kt
  support/common/src/main/kotlin/kr/wooco/woocobe/common/event/EventContext.kt
Labels: refactor, feature

#217 fix: FCM 전송시 디바이스 토큰이 없는 경우 발생하는 예외 해결
  core/src/main/kotlin/kr/wooco/woocobe/core/notification/application/service/NotificationQueryService.kt
Labels: fix

#219 refactor: 장소 리뷰 도메인 전반 리팩터링 (평점 타입 전환, 매퍼 객체화, 한줄평 로직 개선)
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/port/in/result/PlaceReviewWithPlaceResult.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/port/in/result/PlaceReviewWithWriterResult.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/service/PlaceReviewCommandService.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/domain/entity/PlaceOneLineReview.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/domain/entity/PlaceReview.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/domain/vo/PlaceReviewRating.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/place/PlacePersistenceAdapter.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/place/PlacePersistenceMapper.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/placereview/PlaceOneLineReviewPersistenceMapper.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/placereview/PlaceReviewPersistenceAdapter.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/placereview/PlaceReviewPersistenceMapper.kt
Labels: refactor
