Repository team-joytas/wooco-be, pull requests merged in 2025-01, with the labels that each got.

#59 refactor: 소셜 로그인시 PKCE 지원 추가
  src/main/kotlin/kr/wooco/woocobe/auth/domain/gateway/AuthUserStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/gateway/PkceStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/gateway/SocialAuthClientGateway.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/model/AuthUser.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/model/Pkce.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/model/SocialAuth.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/model/SocialType.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/usecase/GetSocialLoginUrlUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/usecase/SocialLoginUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/client/KakaoOAuthRestClient.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/client/SocialAuthClient.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/client/SocialAuthClientConfig.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/client/SocialAuthResponse.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/client/dto/KakaoOAuthInfoResponse.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/client/kakao/KakaoSocialAuthApiClient.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/client/kakao/KakaoSocialAuthClient.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/client/kakao/KakaoSocialAuthProperties.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/client/kakao/response/KakaoSocialAuthResponse.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/client/kakao/response/KakaoSocialTokenResponse.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/gateway/JpaAuthUserStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/gateway/RedisPkceStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/gateway/RestSocialAuthClientGateway.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/storage/AuthUserEntity.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/storage/AuthUserJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/storage/PkceEntity.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/storage/PkceRedisRepository.kt
  src/main/kotlin/kr/wooco/woocobe/auth/ui/config/AuthIgnorePaths.kt
  src/main/kotlin/kr/wooco/woocobe/auth/ui/web/AuthController.kt
  src/main/kotlin/kr/wooco/woocobe/auth/ui/web/dto/request/LoginRequest.kt
  src/main/kotlin/kr/wooco/woocobe/auth/ui/web/dto/response/SocialLoginUrlResponse.kt
  src/main/resources/application-local.yml
  src/test/kotlin/kr/wooco/woocobe/auth/domain/usecase/GetSocialLoginUrlUseCaseTest.kt
  src/test/kotlin/kr/wooco/woocobe/auth/domain/usecase/SocialLoginUseCaseTest.kt
  src/test/kotlin/kr/wooco/woocobe/auth/domain/usecase/WithdrawUseCaseTest.kt
  src/test/resources/application-test.yml
Labels: refactor, feature

#62 feat: Place ID 목록으로 Place 조회 기능 추가
  src/main/kotlin/kr/wooco/woocobe/place/domain/gateway/PlaceStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/gateway/JpaPlaceStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceJpaRepository.kt
Labels: feature

#63 refactor: 코스 인프라 로직 리팩토링 및 도메인 로직 추가
  src/main/kotlin/kr/wooco/woocobe/course/domain/gateway/CourseCommentStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/gateway/CourseStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/gateway/InterestCourseStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/model/Course.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/model/CourseCategory.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/model/CourseComment.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/model/CoursePlace.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/model/InterestCourse.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/AddCourseCommentUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/AddCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/AddInterestCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/DeleteCourseCommentUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/DeleteCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/DeleteInterestCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetAllCourseCommentUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetAllCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetAllMyCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetAllMyInterestCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/UpdateCourseCommentUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/UpdateCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/gateway/CourseCommentStorageGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/gateway/CourseStorageGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/gateway/InterestCourseStorageGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/gateway/JpaCourseCommentStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/gateway/JpaCourseStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/gateway/JpaInterestCourseStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseCategoryEntity.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseCategoryJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseCategoryStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseCommentEntity.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseCommentJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseCommentStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseCustomRepositoryImpl.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseEntity.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CoursePlaceStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/InterestCourseEntity.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/InterestCourseStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/entity/CourseCategoryJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/entity/CourseCommentJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/entity/CourseJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/entity/CoursePlaceJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/entity/InterestCourseJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/repository/CourseCategoryJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/repository/CourseCommentJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/repository/CourseCustomRepository.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/repository/CourseCustomRepositoryImpl.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/repository/CourseJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/repository/CoursePlaceJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/repository/InterestCourseJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/CourseApiController.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/CourseController.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/facade/CourseFacadeService.kt
Labels: refactor, feature

#66 fix: 코스 장소 순서 컬럼명 수정
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/entity/CoursePlaceJpaEntity.kt
Labels: fix

#68 feat: 플랜 CRUD 기능 추가 및 수정, 패키지 구조 리팩토링
  src/main/kotlin/kr/wooco/woocobe/plan/domain/gateway/PlanStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/model/Plan.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/model/PlanCategory.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/model/PlanPlace.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/model/PlanRegion.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/usecase/AddPlanUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/usecase/DeletePlanUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/usecase/GetPlanUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/usecase/UpdatePlanUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/gateway/JpaPlanStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/gateway/PlanStorageGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/PlanCategoryStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/PlanEntity.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/PlanJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/PlanPlaceStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/PlanStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/entity/PlanCategoryJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/entity/PlanJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/entity/PlanPlaceJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/repository/PlanCategoryJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/repository/PlanJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/repository/PlanPlaceJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/plan/ui/web/controller/PlanApi.kt
  src/main/kotlin/kr/wooco/woocobe/plan/ui/web/controller/PlanController.kt
  src/main/kotlin/kr/wooco/woocobe/plan/ui/web/controller/request/AddPlanRequest.kt
  src/main/kotlin/kr/wooco/woocobe/plan/ui/web/controller/request/UpdatePlanRequest.kt
  src/main/kotlin/kr/wooco/woocobe/plan/ui/web/controller/response/GetAllPlanResponse.kt
  src/main/kotlin/kr/wooco/woocobe/plan/ui/web/controller/response/GetPlanResponse.kt
  src/main/kotlin/kr/wooco/woocobe/plan/ui/web/dto/request/AddPlanRequest.kt
  src/main/kotlin/kr/wooco/woocobe/plan/ui/web/dto/request/UpdatePlanRequest.kt
  src/main/kotlin/kr/wooco/woocobe/plan/ui/web/facade/PlanFacadeService.kt
Labels: refactor, feature

#71 feat: 이미지 업로드 기능 추가
  build.gradle.kts
  gradle.properties
  src/main/kotlin/kr/wooco/woocobe/image/domain/gateway/ImageClientGateway.kt
  src/main/kotlin/kr/wooco/woocobe/image/domain/model/Image.kt
  src/main/kotlin/kr/wooco/woocobe/image/domain/model/ImageKey.kt
  src/main/kotlin/kr/wooco/woocobe/image/domain/usecase/GetImageUploadUrlUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/image/infrastructure/client/S3ClientHandler.kt
  src/main/kotlin/kr/wooco/woocobe/image/infrastructure/client/S3ClientProperties.kt
  src/main/kotlin/kr/wooco/woocobe/image/infrastructure/gateway/ImageClientGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/image/ui/web/controller/ImageApi.kt
  src/main/kotlin/kr/wooco/woocobe/image/ui/web/controller/ImageController.kt
  src/main/kotlin/kr/wooco/woocobe/image/ui/web/controller/response/ImageUploadUrlResponse.kt
  src/main/kotlin/kr/wooco/woocobe/image/ui/web/facade/ImageFacadeService.kt
  src/main/resources/application-local.yml
  src/test/resources/application-test.yml
Labels: feature

#75 refactor: 인증 도메인 레이어 컨벤션 일관화
  src/main/kotlin/kr/wooco/woocobe/auth/domain/gateway/AuthTokenStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/gateway/AuthUserStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/gateway/PkceStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/gateway/TokenProviderGateway.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/model/AuthToken.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/model/SocialType.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/usecase/LogoutUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/usecase/ReissueTokenUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/usecase/SocialLoginUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/usecase/WithdrawUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/cache/AuthTokenCacheMapper.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/cache/PkceCacheMapper.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/cache/entity/AuthTokenRedisEntity.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/cache/entity/PkceRedisEntity.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/cache/repository/AuthTokenRedisRepository.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/cache/repository/PkceRedisRepository.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/gateway/AuthTokenStorageGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/gateway/AuthUserStorageGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/gateway/JpaAuthUserStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/gateway/PkceStorageGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/gateway/RedisAuthTokenStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/gateway/RedisPkceStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/gateway/SocialAuthClientGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/gateway/TokenProviderGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/storage/AuthTokenEntity.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/storage/AuthUserEntity.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/storage/AuthUserJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/storage/AuthUserStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/storage/PkceEntity.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/storage/entity/AuthUserJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/storage/repository/AuthUserJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/token/JWTProvider.kt
  src/main/kotlin/kr/wooco/woocobe/auth/ui/web/config/AuthIgnorePaths.kt
  src/main/kotlin/kr/wooco/woocobe/auth/ui/web/config/WebSecurityConfig.kt
  src/main/kotlin/kr/wooco/woocobe/auth/ui/web/controller/AuthApi.kt
  src/main/kotlin/kr/wooco/woocobe/auth/ui/web/controller/AuthController.kt
  src/main/kotlin/kr/wooco/woocobe/auth/ui/web/controller/request/LoginRequest.kt
  src/main/kotlin/kr/wooco/woocobe/auth/ui/web/controller/response/ReissueTokenResponse.kt
  src/main/kotlin/kr/wooco/woocobe/auth/ui/web/controller/response/SocialLoginResponse.kt
  src/main/kotlin/kr/wooco/woocobe/auth/ui/web/controller/response/SocialLoginUrlResponse.kt
  src/main/kotlin/kr/wooco/woocobe/auth/ui/web/dto/request/LoginRequest.kt
  src/main/kotlin/kr/wooco/woocobe/auth/ui/web/filter/JwtAuthenticationFilter.kt
  src/main/kotlin/kr/wooco/woocobe/common/ui/config/SwaggerConfig.kt
  src/main/kotlin/kr/wooco/woocobe/common/utils/CookieExtensions.kt
  src/main/resources/application-local.yml
  src/test/kotlin/kr/wooco/woocobe/auth/domain/usecase/LogoutUseCaseTest.kt
  src/test/kotlin/kr/wooco/woocobe/auth/domain/usecase/ReissueTokenUseCaseTest.kt
  src/test/kotlin/kr/wooco/woocobe/auth/domain/usecase/SocialLoginUseCaseTest.kt
  src/test/kotlin/kr/wooco/woocobe/auth/domain/usecase/WithdrawUseCaseTest.kt
  src/test/resources/application-test.yml
Labels: refactor

#78 refactor: 플랜 식별자 생성 전략 수정
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/gateway/PlanStorageGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/PlanCategoryStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/PlanPlaceStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/PlanStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/entity/PlanCategoryJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/entity/PlanJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/entity/PlanPlaceJpaEntity.kt
Labels: fix, refactor

#80 refactor: 회원 레이어 컨벤션 일관화
  src/main/kotlin/kr/wooco/woocobe/user/domain/gateway/UserStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/user/domain/usecase/GetAllUserUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/user/domain/usecase/GetUserUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/user/domain/usecase/UpdateUserUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/user/infrastructure/gateway/JpaUserStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/user/infrastructure/gateway/UserStorageGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/user/infrastructure/storage/UserEntity.kt
  src/main/kotlin/kr/wooco/woocobe/user/infrastructure/storage/UserJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/user/infrastructure/storage/UserStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/user/infrastructure/storage/entity/UserJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/user/infrastructure/storage/repository/UserJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/user/ui/web/UserController.kt
  src/main/kotlin/kr/wooco/woocobe/user/ui/web/controller/UserApi.kt
  src/main/kotlin/kr/wooco/woocobe/user/ui/web/controller/UserController.kt
  src/main/kotlin/kr/wooco/woocobe/user/ui/web/controller/request/UpdateUserRequest.kt
  src/main/kotlin/kr/wooco/woocobe/user/ui/web/controller/response/GetCurrentUserResponse.kt
  src/main/kotlin/kr/wooco/woocobe/user/ui/web/dto/request/UpdateUserProfileRequest.kt
  src/main/kotlin/kr/wooco/woocobe/user/ui/web/dto/response/GetCurrentUserResponse.kt
  src/main/kotlin/kr/wooco/woocobe/user/ui/web/facade/UserFacadeService.kt
  src/test/kotlin/kr/wooco/woocobe/auth/domain/usecase/SocialLoginUseCaseTest.kt
  src/test/kotlin/kr/wooco/woocobe/auth/domain/usecase/WithdrawUseCaseTest.kt
  src/test/kotlin/kr/wooco/woocobe/user/domain/usecase/GetUserUseCaseTest.kt
  src/test/kotlin/kr/wooco/woocobe/user/domain/usecase/UpdateUserUseCaseTest.kt
Labels: refactor

#83 feat: GetAllPlaceUseCase 추가
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/GetAllPlaceUseCase.kt
Labels: feature

#87 fix: 개발 환경 배포 스크립트 수정
  .github/workflows/deploy-dev.yml
  Dockerfile-dev
Labels: fix

#89 refactor: 사용하지 않는 아이디 생성 클래스 삭제
  Dockerfile
  src/main/kotlin/kr/wooco/woocobe/common/infrastructure/storage/IdGenerator.kt
  src/main/kotlin/kr/wooco/woocobe/common/infrastructure/storage/IdGeneratorConfig.kt
Labels: refactor

#90 refactor: 장소 도메인 메서드 컨벤션 수정 및 리팩토링
  src/main/kotlin/kr/wooco/woocobe/place/domain/gateway/PlaceStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/model/Place.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/AddPlaceReviewUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/AddPlaceUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/DeletePlaceReviewUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/UpdatePlaceReviewUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/gateway/PlaceReviewStorageGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/gateway/PlaceStorageGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceReviewStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/entity/PlaceJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/entity/PlaceOneLineReviewJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/entity/PlaceReviewImageJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/entity/PlaceReviewJpaEntity.kt
Labels: refactor, style

#95 feat: 코스 API 컨트롤러 및 퍼샤드 레이어 추가
  src/main/kotlin/kr/wooco/woocobe/course/domain/gateway/InterestCourseStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/AddCourseCommentUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/AddCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/CheckInterestCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/DeleteInterestCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetAllInterestCourseIdUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetAllMyCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/gateway/CourseStorageGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/gateway/InterestCourseStorageGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseCategoryStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseCommentStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CoursePlaceStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/InterestCourseStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/entity/CourseCategoryJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/entity/CourseCommentJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/entity/CourseJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/entity/CoursePlaceJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/entity/InterestCourseJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/repository/InterestCourseJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/CourseApi.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/CourseApiController.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/CourseCommentApi.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/CourseCommentController.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/CourseController.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/request/CreateCourseCommentRequest.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/request/CreateCourseRequest.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/request/UpdateCourseCommentRequest.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/request/UpdateCourseRequest.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/response/CourseCommentDetailResponse.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/response/CourseDetailResponse.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/response/CreateCourseCommentResponse.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/response/CreateCourseResponse.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/facade/CourseCommandFacade.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/facade/CourseCommentCommandFacade.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/facade/CourseCommentQueryFacade.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/facade/CourseFacadeService.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/facade/CourseQueryFacade.kt
Labels: feature

#102 feat: 회원 소개 기능 및 다른 회원 조회 API 추가
  src/main/kotlin/kr/wooco/woocobe/user/domain/model/User.kt
  src/main/kotlin/kr/wooco/woocobe/user/domain/usecase/UpdateUserUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/user/infrastructure/storage/UserStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/user/infrastructure/storage/entity/UserJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/user/ui/web/controller/UserApi.kt
  src/main/kotlin/kr/wooco/woocobe/user/ui/web/controller/UserController.kt
  src/main/kotlin/kr/wooco/woocobe/user/ui/web/controller/request/UpdateUserRequest.kt
  src/main/kotlin/kr/wooco/woocobe/user/ui/web/controller/response/GetCurrentUserResponse.kt
  src/main/kotlin/kr/wooco/woocobe/user/ui/web/controller/response/UserDetailResponse.kt
  src/main/kotlin/kr/wooco/woocobe/user/ui/web/facade/UserFacadeService.kt
  src/test/kotlin/kr/wooco/woocobe/user/domain/usecase/GetUserUseCaseTest.kt
  src/test/kotlin/kr/wooco/woocobe/user/domain/usecase/UpdateUserUseCaseTest.kt
Labels: feature

#106 feat: 장소 도메인 UI 레이어 구현
  src/main/kotlin/kr/wooco/woocobe/place/domain/model/Place.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/AddPlaceReviewUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/AddPlaceUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/GetAllMyPlaceReviewUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/GetOneLineReviewStatsUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/entity/PlaceJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/PlaceApi.kt
  src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/PlaceController.kt
  src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/PlaceReviewApi.kt
  src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/PlaceReviewController.kt
  src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/request/CreatePlaceRequest.kt
  src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/request/CreatePlaceReviewRequest.kt
  src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/request/UpdatePlaceReviewRequest.kt
  src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/response/CreatePlaceResponse.kt
  src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/response/CreatePlaceReviewResponse.kt
  src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/response/PlaceDetailResponse.kt
  src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/response/PlaceOneLineReviewStatDetailResponse.kt
  src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/response/PlaceReviewDetailsResponse.kt
  src/main/kotlin/kr/wooco/woocobe/place/ui/web/facade/PlaceCommandFacade.kt
  src/main/kotlin/kr/wooco/woocobe/place/ui/web/facade/PlaceQueryFacade.kt
  src/main/kotlin/kr/wooco/woocobe/place/ui/web/facade/PlaceReviewCommandFacade.kt
  src/main/kotlin/kr/wooco/woocobe/place/ui/web/facade/PlaceReviewQueryFacade.kt
Labels: feature

#108 refactor: 리뷰 이미지 처리 로직 개선 및 함수명 수정
  src/main/kotlin/kr/wooco/woocobe/place/domain/model/Place.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/AddPlaceReviewUseCase.kt
Labels: refactor

#112 refactor: 코스 예외 처리 추가 및 방문 날짜 추가
  src/main/kotlin/kr/wooco/woocobe/course/domain/exception/CourseCommentExceptions.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/exception/CourseExceptions.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/model/Course.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/model/CourseCategory.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/model/CourseComment.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/model/CourseSortCondition.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/AddCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/AddInterestCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetAllUserCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetAllUserInterestCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/UpdateCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/gateway/CourseCommentStorageGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/gateway/CourseStorageGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/entity/CourseJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/CourseApi.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/CourseCommentController.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/CourseController.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/request/CreateCourseRequest.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/request/UpdateCourseRequest.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/response/CourseDetailResponse.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/facade/CourseQueryFacade.kt
Labels: refactor

#113 refactor: 인증 예외 처리 추가 및 미인증 경로 추가
  src/main/kotlin/kr/wooco/woocobe/auth/domain/exception/AuthExceptions.kt
  src/main/kotlin/kr/wooco/woocobe/auth/domain/model/SocialType.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/cache/repository/PkceRedisRepository.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/client/SocialAuthClientConfig.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/gateway/AuthTokenStorageGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/gateway/PkceStorageGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/gateway/SocialAuthClientGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/auth/infrastructure/token/JWTProvider.kt
  src/main/kotlin/kr/wooco/woocobe/auth/ui/web/config/AuthIgnorePaths.kt
  src/main/kotlin/kr/wooco/woocobe/auth/ui/web/controller/AuthApi.kt
Labels: refactor

#114 refactor: 회원 예외 처리 추가
  src/main/kotlin/kr/wooco/woocobe/course/domain/exception/CourseExceptions.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/gateway/InterestCourseStorageGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/user/domain/exception/UserExceptions.kt
  src/main/kotlin/kr/wooco/woocobe/user/infrastructure/gateway/UserStorageGatewayImpl.kt
Labels: refactor

#116 refactor: 장소 도메인 예외 처리 추가 및 개선
  src/main/kotlin/kr/wooco/woocobe/place/domain/exception/PlaceExceptions.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/exception/PlaceReviewExceptions.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/model/Place.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/model/PlaceOneLineReview.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/model/PlaceOneLineReviewStat.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/model/PlaceReview.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/AddPlaceReviewUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/domain/usecase/UpdatePlaceReviewUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/gateway/PlaceReviewStorageGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/gateway/PlaceStorageGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceOneLineReviewStatStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceOneLineReviewStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/PlaceReviewStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/entity/PlaceOneLineReviewJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/entity/PlaceReviewJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/place/infrastructure/storage/repository/PlaceOneLineReviewJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/PlaceReviewApi.kt
  src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/PlaceReviewController.kt
  src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/request/CreatePlaceReviewRequest.kt
  src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/request/UpdatePlaceReviewRequest.kt
  src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/response/PlaceOneLineReviewStatDetailResponse.kt
  src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/response/PlaceReviewDetailsResponse.kt
Labels: refactor

#118 feat: 플랜 도메인 커스텀 예외 추가 및 응답 형식 통일
  src/main/kotlin/kr/wooco/woocobe/plan/domain/exception/PlanExceptions.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/model/Plan.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/model/PlanCategory.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/usecase/AddPlanUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/plan/domain/usecase/UpdatePlanUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/gateway/PlanStorageGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/PlanStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/plan/infrastructure/storage/entity/PlanJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/plan/ui/web/controller/request/CreatePlanRequest.kt
  src/main/kotlin/kr/wooco/woocobe/plan/ui/web/controller/request/UpdatePlanRequest.kt
  src/main/kotlin/kr/wooco/woocobe/plan/ui/web/controller/response/PlanDetailResponse.kt
Labels: refactor, feature

#120 refactor: 코스 및 장소 API 응답 형식 수정
  src/main/kotlin/kr/wooco/woocobe/course/domain/gateway/CourseStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/model/Course.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/AddCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetAllCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/UpdateCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/gateway/CourseStorageGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/CourseStorageMapper.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/entity/CourseJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/entity/InterestCourseJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/repository/CourseCustomRepository.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/repository/CourseCustomRepositoryImpl.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/CourseApi.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/CourseController.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/request/CreateCourseRequest.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/request/UpdateCourseRequest.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/response/CourseDetailResponse.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/facade/CourseQueryFacade.kt
  src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/response/CreatePlaceResponse.kt
  src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/response/CreatePlaceReviewResponse.kt
  src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/response/PlaceDetailResponse.kt
  src/main/kotlin/kr/wooco/woocobe/place/ui/web/controller/response/PlaceReviewDetailsResponse.kt
Labels: refactor

#124 refactor: 관심 코스 조회시 최대 개수 지정 추가
  src/main/kotlin/kr/wooco/woocobe/course/domain/gateway/InterestCourseStorageGateway.kt
  src/main/kotlin/kr/wooco/woocobe/course/domain/usecase/GetAllUserInterestCourseUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/gateway/InterestCourseStorageGatewayImpl.kt
  src/main/kotlin/kr/wooco/woocobe/course/infrastructure/storage/repository/InterestCourseJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/CourseApi.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/controller/CourseController.kt
  src/main/kotlin/kr/wooco/woocobe/course/ui/web/facade/CourseQueryFacade.kt
Labels: refactor

#125 refactor: 인증 적용 경로 및 플랜 조회 API 응답 수정
  src/main/kotlin/kr/wooco/woocobe/auth/ui/web/config/AuthIgnorePaths.kt
  src/main/kotlin/kr/wooco/woocobe/plan/ui/web/controller/response/PlanDetailResponse.kt
Labels: refactor

#126 feat: 회원 선호 지역 기능 추가
  src/main/kotlin/kr/wooco/woocobe/region/adapter/in/web/RegionApi.kt
  src/main/kotlin/kr/wooco/woocobe/region/adapter/in/web/RegionController.kt
  src/main/kotlin/kr/wooco/woocobe/region/adapter/in/web/request/CreatePreferenceRegionRequest.kt
  src/main/kotlin/kr/wooco/woocobe/region/adapter/in/web/response/CreatePreferenceRegionResponse.kt
  src/main/kotlin/kr/wooco/woocobe/region/adapter/in/web/response/PreferenceDetailResponse.kt
  src/main/kotlin/kr/wooco/woocobe/region/adapter/out/presistence/PreferenceRegionMapper.kt
  src/main/kotlin/kr/wooco/woocobe/region/adapter/out/presistence/PreferenceRegionPersistenceAdapter.kt
  src/main/kotlin/kr/wooco/woocobe/region/adapter/out/presistence/entity/PreferenceRegionJpaEntity.kt
  src/main/kotlin/kr/wooco/woocobe/region/adapter/out/presistence/repository/PreferenceRegionJpaRepository.kt
  src/main/kotlin/kr/wooco/woocobe/region/application/command/port/in/AddPreferenceRegionUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/region/application/command/port/in/DeletePreferenceRegionUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/region/application/command/port/out/DeletePreferenceRegionPort.kt
  src/main/kotlin/kr/wooco/woocobe/region/application/command/port/out/LoadPreferenceRegionPort.kt
  src/main/kotlin/kr/wooco/woocobe/region/application/command/port/out/SavePreferenceRegionPort.kt
  src/main/kotlin/kr/wooco/woocobe/region/application/command/service/RegionCommandService.kt
  src/main/kotlin/kr/wooco/woocobe/region/application/query/port/in/GetAllPreferenceRegionUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/region/application/query/port/in/GetPreferenceRegionUseCase.kt
  src/main/kotlin/kr/wooco/woocobe/region/application/query/port/out/LoadPreferenceRegionDataPort.kt
  src/main/kotlin/kr/wooco/woocobe/region/application/query/service/RegionQueryService.kt
  src/main/kotlin/kr/wooco/woocobe/region/application/query/service/dto/PreferenceRegionData.kt
  src/main/kotlin/kr/wooco/woocobe/region/domain/entity/PreferenceRegion.kt
  src/main/kotlin/kr/wooco/woocobe/region/domain/exception/RegionExceptions.kt
Labels: feature

#130 refactor: 더 이상 사용하지 않는 TSID 라이브러리 및 기본 엔티티 클래스 삭제
  build.gradle.kts
  gradle.properties
  src/main/kotlin/kr/wooco/woocobe/common/infrastructure/storage/BaseTimeEntity.kt
Labels: refactor
