Repository team-joytas/wooco-be, pull requests merged in 2025-03, with the labels that each got.

#192 fix: 코스 상세 조회시 관심 여부 반환 버그 수정
  core/src/main/kotlin/kr/wooco/woocobe/core/course/application/service/CourseQueryService.kt
Labels: fix

#198 refactor: 장소 리뷰 API 추가 및 평점 계산 로직 개선, 이미지 저장 예외 처리 추가
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/place/response/PlaceDetailResponse.kt
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/placereview/PlaceReviewApi.kt
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/placereview/PlaceReviewController.kt
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/placereview/response/ExistsPlaceReviewWriterResponse.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/course/application/service/CourseQueryService.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/place/application/handler/PlaceEventHandler.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/place/application/port/in/DecreaseReviewCountUseCase.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/place/application/port/in/IncreasePlaceReviewCountUseCase.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/place/application/port/in/UpdateAverageRatingUseCase.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/place/application/port/in/UpdateReviewStatsUseCase.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/place/application/port/out/PlaceCommandPort.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/place/application/port/out/PlaceQueryPort.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/place/application/service/PlaceCommandService.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/place/application/service/PlaceQueryService.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/place/domain/entity/Place.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/port/in/ExistsPlaceReviewWriterUseCase.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/port/out/DeleteAllPlaceOneLineReviewPersistencePort.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/port/out/DeletePlaceReviewPersistencePort.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/port/out/LoadPlaceOneLineReviewPersistencePort.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/port/out/LoadPlaceReviewPersistencePort.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/port/out/PlaceReviewCommandPort.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/port/out/PlaceReviewQueryPort.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/port/out/SaveAllPlaceOneLineReviewPersistencePort.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/port/out/SavePlaceReviewPersistencePort.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/service/PlaceReviewCommandService.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/service/PlaceReviewQueryService.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/application/service/dto/PlaceReviewStats.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/domain/entity/PlaceReview.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/domain/event/PlaceReviewCreateEvent.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/domain/event/PlaceReviewDeleteEvent.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/placereview/domain/event/PlaceReviewUpdateEvent.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/plan/application/service/PlanQueryService.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/place/PlacePersistenceAdapter.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/placereview/PlaceOneLineReviewPersistenceAdapter.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/placereview/PlaceReviewPersistenceAdapter.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/placereview/repository/PlaceReviewJpaRepository.kt
Labels: refactor, feature

#201 refactor: 플랜 도메인 포트 및 어댑터 등 컨벤션 통일
  core/src/main/kotlin/kr/wooco/woocobe/core/plan/application/port/out/DeletePlanPersistencePort.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/plan/application/port/out/PlanCommandPort.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/plan/application/port/out/PlanQueryPort.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/plan/application/scheduler/PlanScheduler.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/plan/application/service/PlanCommandService.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/plan/application/service/PlanQueryService.kt
  core/src/main/kotlin/kr/wooco/woocobe/core/plan/domain/entity/Plan.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/plan/PlanPersistenceAdapter.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/plan/PlanPersistenceMapper.kt
  infrastructure/mysql/src/main/kotlin/kr/wooco/woocobe/mysql/plan/PlanPlacePersistenceMapper.kt
Labels: refactor

#206 fix: PreAuthorize 버그 해결 및 엑츄에이터 포트 수정
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/auth/AuthController.kt
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/common/config/WebSecurityConfig.kt
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/common/security/SecurityIgnorePath.kt
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/course/CourseController.kt
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/coursecomment/CourseCommentController.kt
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/image/ImageController.kt
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/notification/NotificationController.kt
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/place/PlaceController.kt
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/placereview/PlaceReviewController.kt
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/plan/PlanController.kt
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/region/RegionController.kt
  bootstrap/api/src/main/kotlin/kr/wooco/woocobe/api/user/UserController.kt
  infrastructure/rest/src/main/resources/application-rest.yml
  support/metric/src/main/resources/application-metric.yml
Labels: fix, refactor
